version: '3.9'
services:
  prod-web:
    container_name: youtube-clone-frontend
    image: tpavz/youtube-clone-frontend
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    ports:
      - '80:80'